### ISSUE TITLE
Get expression matrix

### ISSUE THREAD

**Issue by kiristern** [SomaLogic/Canopy#2]
Hello!

How can I obtain the sample x gene matrix?

There is documentation for the R function `eSet <- adat2eSet(example_data)` but I can't seem to extract just the expression matrix in python. 

Thanks!

**Comment by kiristern** [comment]
ah, i just simply did `X = np.array(adat)` and got what i wanted.

**Comment by stufield** [comment]
Do you mind if we keep this issue open for a while in case others have a similar issue and will make it easier to find?
@tjohnson-somalogic , is this the preferred way to get the RFU expression matrix in `Canopy`? Or is there a better way (e.g. a helper to extract the matrix).

**Comment by tjohnson-somalogic** [comment]
Hi @kiristern! Thanks for your interest in using Canopy.

Your solution is a good solution; however, it does change your `adat` from a canopy.Adat object to a [numpy.ndarray ](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) object.  This will impact how you can use that object downstream.  For most applications this is totally fine, most things you want to do with a DataFrame can also be done with an ndarray. If you want to stay in DataFrame space there are a few options.

The canopy.Adat object is a child of the pandas.DataFrame.  When you input `adat` you are are accessing the RFU or (sample x gene) matrix. For example `log_adat = np.log10(adat)` would calculate the log10 of the RFU matrix.  The row and column metada will not be included in this activity.

Both the row and column indices on the canopy.Adat object are [pandas.MultiIndex](https://pandas.pydata.org/docs/user_guide/advanced.html) objects. When you perform actions on the RFU matrix they are not involved or impacted.  They can be large though and some people find them visually distracting.

I find a lot of utility in keeping the multiIndex.  For instance, it can be helpful in conjunction with functions like [pd.DataFrame.groupby](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html). If you don't like them or don't need them you could remove them like this:
```
# creating the adat:
adat = canopy.read_adat('my_results.adat')
#  The adat object allows you to access the RFU matrix by calling the variable name:
log_adat = np.log10(adat)
# To get rid of the MultiIndex you can set a new index from one of the levels:
adat.set_index(adat.index.get_level_values('SampleId'), inplace=True)
adat.columns = adat.columns.get_level_values('SeqId')
```
The result will still be a canopy.Adat object and a pandas.DataFrame object but it will have simplified index and column structures.  This might be a good solution if you don't like the extra metadata but do want to use DataFrame specific functionality.

**Comment by kiristern** [comment]
@tjohnson-somalogic thank you so much for taking the time to follow up and provide additional solutions!
