### ISSUE TITLE
Support pandas > 2.0.3 on python 3.11

### ISSUE THREAD

**Issue by akotlar** [SomaLogic/Canopy#4]
In https://github.com/SomaLogic/Canopy/commit/23470d29c8b02dd37dfc9576b2e22b16be6fb797 you remove Pandas > 2.0.* support in Python 3.11.

Python 3.12 is not yet widely supported, and more recent Pandas (> 2.0.*) versions continue to support Python 3.11. 

 Would it be possible to restore Pandas > 2.0.* support on Python < 3.12?

**Comment by kyoung73** [comment]
Hi @akotlar. Thank you for bringing this to our attention and opening an issue. We will be pushing out a fix shortly!

**Comment by akotlar** [comment]
> Hi @akotlar. Thank you for bringing this to our attention and opening an issue. We will be pushing out a fix shortly!

Awesome thanks!

**Comment by kyoung73** [comment]
@akotlar We have pushed the fix in: 2c5286a32095dddee536a0806e5c8899820edc14. Thank you again for bringing it up! Please let us know if there are any other questions or concerns.

**Comment by akotlar** [comment]
Awesome thanks! Then I'll close my PR

**Comment by akotlar** [comment]
Btw, so far the library is a pleasure to use. Refreshing in bioinformatics
